spring:
  application:
    name: DemasAPI

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /

google:
  maps:
    api-key: ${GOOGLE_API_KEY}

health-check:
  url: ${HEALTH_CHECK_URL}

server:
  forward-headers-strategy: native

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.index: TRACE