spring:
  application:
    name: DemasAPI

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs

logging:
  level:
    org.springframework.web: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.springframework.data.mongodb.core.index: TRACE